name: Advanced Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Hiroshi0Nohara
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Tokyo
          plugin_lines: yes
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
